version: "3"

services:
  backend:
    build: .
    volumes:
      - "./prod.yml:/app/prod.yml"
      - "./auth:/app/auth"
    expose:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:17.5
    expose:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgressdljkmbvljhkd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
