version: "3"

services:
  backend:
    image: ghcr.io/alexereh/lazyecm/api:latest
    volumes:
      - "./prod.yml:/app/prod.yml"
      - "./auth:/app/auth"
    expose:
      - "58080:58080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    image: ghcr.io/alexereh/lazyecm/frontend:latest
    expose:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: 1w_panel_nginx
    logging:
      driver: "json-file"
      options:
        max-size: "10m"    # максимум на один файл
        max-file: "3"
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    restart: unless-stopped

  adminer:
    image: adminer
    restart: always
    ports:
      - "5080:8080"

  postgres:
    image: postgres:17.5
    expose:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgressdljkmbvljhkd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
